---
- name: My test Playbook
  hosts: all
  become: yes

  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
  - name: start service
    service:
      name: httpd
      state: started
